max_draw_elements = 200
max_scene_objects = 100
max_textures = 200
max_materials = 200
command_size = 5
max_point_lights = 5
max_spot_lights = 5
shadowQuality = LOW
lightingQuality = LOW
backendType = OPENGL

