import org.apache.tools.ant.taskdefs.condition.Os

plugins {
    id 'java'
    id 'maven-publish'
    id 'application'
}

String lwjglNatives = "";

if(Os.isFamily(Os.FAMILY_WINDOWS)) {
    lwjglNatives = "natives-windows";
} else if (Os.isFamily(Os.FAMILY_UNIX)) {
    lwjglNatives = "natives-linux";
}

repositories {
    mavenCentral()
    maven { url = "https://central.sonatype.com/repository/maven-snapshots" }
}

dependencies {
    implementation project(':relic-engine.heirloom')
    implementation project(':relic-engine.curio')

    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"

    implementation "org.lwjgl:lwjgl-glfw"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"

    implementation "org.lwjgl:lwjgl-opengl"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"

    implementation "org.lwjgl:lwjgl-vulkan"

    implementation "org.lwjgl:lwjgl-shaderc"
    runtimeOnly "org.lwjgl:lwjgl-shaderc::$lwjglNatives"

    implementation "org.lwjgl:lwjgl-assimp"
    runtimeOnly "org.lwjgl:lwjgl-assimp::$lwjglNatives"

    implementation "io.github.spair:imgui-java-app:${imguiVersion}"
    runtimeOnly "io.github.spair:imgui-java-app:${imguiVersion}"

    implementation "net.bytebuddy:byte-buddy:1.18.12"

    implementation 'org.tinylog:tinylog-api:2.7.0'
    implementation 'org.tinylog:tinylog-impl:2.7.0'

    implementation 'io.github.classgraph:classgraph:4.8.192'
    implementation "org.joml:joml:${jomlVersion}"
}

application {
    mainClass = 'net.ice.relic.common.test.VulkanTest'
}

jar {
    from ('./src/main/java') {
        include 'META-INF/services/org.tinylog.writers.Writer'
    }
    manifest {
        attributes(
                'Main-Class': 'net.ice.relic.common.test.VulkanTest'
        )
    }
}

tasks.named('jar') {
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    eachFile { FileCopyDetails details ->
        if (details.path.startsWith('META-INF/services/')) {
            details.duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.register('buildAgent', Jar) {
    group = 'build'
    description = 'Generates manifest and builds a ByteBuddy agent'

    archiveClassifier = 'agent'

    manifest {
        attributes(
                'Premain-Class': 'net.ice.relic.agent.RelicAgent',
                'Agent-Class': 'net.ice.relic.agent.RelicAgent',
                'Can-Redefine-Classes': 'true',
                'Can-Retransform-Classes': 'true'
        )
    }

    from sourceSets.main.output

    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    } {
        exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named('distZip') {
    enabled = false
    entryCompression = ZipEntryCompression.STORED
}

tasks.named("distTar") {
    enabled = false
}

